import React from 'react';
import { useLocation } from 'react-router-dom';
import Blogdata from './Blogdata';
import './Blogdetail.css'
import Breadcrumb from '../Breadcrumb';
const Sustainability_competitive_advantage_business_success = () => {
  const location = useLocation();
  const blog = Blogdata.find((item) => item.detailPage === location.pathname);

  if (!blog) {
    return <h2>Blog Not Found</h2>;
  }
  const breadcrumbItems = [
    { label: 'Home', link: '/', active: false },
    { label: 'Blog', link: '/blogs', active: false },
    { label: blog.title, active: true }, // Active item does not need a link
  ];
  return (
    <>
  
    <div className="container">
    <Breadcrumb items={breadcrumbItems} />
      <div className="blog-detail">
        <div className='outer-blog-img'>
        <img src={blog.image} alt={blog.title} className="blog-detail-image" />
        </div>
        <h2 className='mt-3'>{blog.title}</h2>
        <div className="blog-meta mb-3 d-flex justify-content-between align-items-center mt-3">
          <span>
            <b>Author:</b> {blog.author}
          </span>
          <span >
            <b>Published Date:</b> {blog.date}
          </span>
        </div>
       <p>Sustainability comprises value creation, which is accomplished by incorporating environmental, social, and governance targets into the business plan by using a model that promotes long-term value for each party involved. This model is executed to meet sustainable development goals (SDG), and it utilizes specific indicators to direct management throughout the company and subsidiaries.</p>
       <h5>How Businesses Can Succeed by Embracing Sustainability:</h5>
       <p>70% of CO2 emissions come from industries. They have the responsibility to take action and address their environmental impact. Businesses should focus on developing sustainability strategies. In SDG there are some goals; by achieving those goals, we can adapt sustainability.</p>
       <p>One of the goals is there that is affordable and clean energy, so burning fossil fuels like coal, oil, and gas is a primary contributor to greenhouse gas emissions and also creates pollution, which can be mitigated by investing in renewable energy and clean technology for a more sustainable energy system.</p>
       <p>Another goal is there that is climate action, so climate change due to various human activities threatens life on the earth; it increases sea levels, changing the weather patterns. If it is not controlled now, the average global temperature will increase beyond 3°C and will adversely affect ecosystems. Businesses and industries take care to lower the emissions they have to take proactive steps to reduce their carbon footprints.</p>
       <p>Conserving life on land is one of the goals, and the aim of this goal is to protect the land and ecosystem, manage forests, and stop the biodiversity. Ecosystems are essential to human survival. Land is degraded due to deforestation, and it increases CO2 emissions.</p>
       <p>Conserve and sustainably use oceans, seas, and marine life; in these goals, the ocean helps to reduce the climate change impact by absorbing CO2 emissions that are generated by human activity. It absorbs nearly 23% CO2, and 90% excess heat is absorbed. Agricultural companies and chemical companies pollute the ocean through chemical runoff. Soil extraction, overfishing, and mining also pollute the ocean. Companies that produce or use plastic contribute to pollution. So companies have to avoid such pollution and take necessary action and reduce the environmental impact.</p>
       <p><b>In conclusion, industries and businesses play a vital role in achieving sustainability. By advancing the Global Sustainable Development Goals and by integrating environmental, social, and governance targets into their strategies, companies can reduce their ecological footprints and also contribute to a resilient and equitable society. There are several goals of sustainable development growth, such as affordable and clean energy, climate action, life on land, and life below water, which are the main areas where businesses and industries can make a substantial impact. Businesses and industries can lead towards a more sustainable future by transitioning to renewable energy, reducing carbon emissions, protecting ecosystems, and addressing marine pollution. Implementing sustainability means more than just reducing risk; it also additionally involves providing long-term value that benefits all parties involved, including communities, investors, and the environment. Businesses and industries must take preventive steps to ensure that they contribute to a healthier planet for future generations because achieving sustainability is a shared objective.</b></p>
      
      </div>
    </div>
    </>
  );
};

export default Sustainability_competitive_advantage_business_success;
